version: '3.1'
services:
  mongo_one:
    container_name: mongo_one
    image: mongo
    command: mongod --replSet rs1
    ports:
    - 30001:27017
    networks:
      - mom
  mongo_two:
    container_name: mongo_two
    image: mongo
    command: mongod --replSet rs1
    ports:
      - 30002:27017
    networks:
      - mom
  mongo_three:
    container_name: mongo_three
    image: mongo
    command: mongod --replSet rs1
    ports:
      - 30003:27017
    networks:
      - mom

  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./zk-multiple-kafka-single/zookeeper/data:/data
      - ./zk-multiple-kafka-single/zookeeper/datalog:/datalog
    networks:
      - mom
  kafka1:
    image: confluentinc/cp-kafka:5.5.0
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./zk-multiple-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - mom

  ms-extractor:
    build: ./services/ms-extractor
    container_name: ms-extractor
    env_file:
      - ./configs/.env
    depends_on:
      - mongo_one
      - mongo_two
      - mongo_three
      - kafka1
    ports:
      - 8080:8080
    volumes:
      - ./services/ms-extractor:/go/src/mom/services/ms-extractor
    environment:
      - MONGO_URI=mongodb://mongo_one:27017,mongo_two:27017,mongo_three:27017/?replicaSet=rs1
      - KAFKA_URI=kafka1:19092
      - DIRECTORY="${MS-EXTRACTOR-DIR}"
#      - MONGO_URI=mongodb://localhost:27017/?replicaSet=rs1&connect=direct
    networks:
      - mom
  ms-consumer:
    build: ./services/ms-consumer
    container_name: ms-consumer
    env_file:
      - ./configs/.env
    depends_on:
      - mongo_one
      - mongo_two
      - mongo_three
      - kafka1
    ports:
      - 8081:8081
    volumes:
      - ./services/ms-consumer:/go/src/mom/services/ms-consumer
    environment:
      - MONGO_URI=mongodb://mongo_one:27017,mongo_two:27017,mongo_three:27017/?replicaSet=rs1
      - KAFKA_URI=kafka1:19092
      - DIRECTORY="${MS-CONSUMER-DIR}"
    #      - MONGO_URI=mongodb://localhost:27017/?replicaSet=rs1&connect=direct
    networks:
      - mom
networks:
  mom:
    driver: bridge